apiVersion: aadee.apps.obaydullahmhs/v1
kind: Aadee
metadata:
  labels:
    app.kubernetes.io/name: aadee
    app.kubernetes.io/instance: aadee-sample
    app.kubernetes.io/part-of: kubebuilder-crd
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: kubebuilder-crd
  name: aadee-sample-2
spec:
  deploymentName: my-deployment
  replicas: 1
  container:
    image: "obaydullahmhs/api-server"
    port: 8080
  service:
    serviceName: "my-bro"
    serviceType: "ClusterIP"
    servicePort: 8080

  # TODO(user): Add fields here
